# Cloud Build configuration para Google Cloud Run
steps:
  # Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/snackbar-app:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/snackbar-app:latest'
      - '.'
    timeout: '1800s'

  # Push da imagem para Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/snackbar-app:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/snackbar-app:latest'

  # Deploy no Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'snackbar-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/snackbar-app:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'DB_HOST=localhost,DB_PORT=3306,DB_NAME=snackbar_db,DB_USERNAME=snackbar_user,SERVER_PORT=8080,JWT_EXPIRATION=86400,SHOW_SQL=false,LOG_LEVEL=INFO'
      - '--set-secrets'
      - 'DB_PASSWORD=db-password:latest,JWT_SECRET=jwt-secret:latest'
    secretEnv: ['DB_PASSWORD', 'JWT_SECRET']

# Secrets do Secret Manager
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/db-password/versions/latest
      env: 'DB_PASSWORD'
    - versionName: projects/$PROJECT_ID/secrets/jwt-secret/versions/latest
      env: 'JWT_SECRET'

# Opções
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '2400s'

images:
  - 'gcr.io/$PROJECT_ID/snackbar-app:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/snackbar-app:latest'

